# Generated by Django 5.2.17 on 2026-09-30 13:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_pedidos_de_marketplace'),
        ('supplies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyStock',
            fields=[
                ('supply', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='stock', serialize=False, to='supplies.supply')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('occurred_on', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=12)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('previous_roll_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='supplies.supply')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=240)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_movements', to='sales.sale')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='supplies.supply')),
                ('receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='supplies.supplyreceipt')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplyreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supply_receipt_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplyreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('unit_cost__gte', 0)), name='supply_receipt_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplymovement',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='supply_movement_nonzero'),
        ),
    ]
