# Generated by Django 5.2.17 on 2026-09-30 14:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_pedidos_de_marketplace'),
        ('supplies', '0002_estoque_compras_insumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply_name', models.CharField(max_length=120)),
                ('requested', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('taken', models.PositiveIntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_lines', to='sales.sale')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='supplies.supply')),
            ],
            options={
                'ordering': ['supply_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('sale', 'supply'), name='sale_supply_unique'), models.CheckConstraint(condition=models.Q(('requested__gt', 0)), name='sale_supply_requested_positive'), models.CheckConstraint(condition=models.Q(('taken__lte', models.F('requested'))), name='sale_supply_taken_le_requested')],
            },
        ),
    ]
