server {
    listen 443 ssl;
    server_name 217.216.82.25;
    ssl_certificate /etc/letsencrypt/live/jalapao-ip/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jalapao-ip/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options SAMEORIGIN always;
    include /etc/nginx/jalapao-locations.conf;
}

server {
    listen 443 ssl;
    server_name jalapao-store.217-216-82-25.sslip.io;
    ssl_certificate /etc/letsencrypt/live/jalapao-domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jalapao-domain/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options SAMEORIGIN always;
    include /etc/nginx/jalapao-locations.conf;
}
