# Generated by Django 5.2.17 on 2026-09-23 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0002_receipt_movement_value_after_movement_value_delta_and_more'),
        ('sales', '0002_saleitem_cost_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='inventory.receipt'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.CheckConstraint(condition=models.Q(('sale__isnull', True), ('receipt__isnull', True), _connector='OR'), name='cash_single_origin'),
        ),
    ]
