# Generated by Django 5.2.17 on 2026-09-29 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashentry_receipt_cashentry_cash_single_origin'),
        ('inventory', '0004_cancelar_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='refund_of_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='inventory.receipt'),
        ),
    ]
