# Generated by Django 5.2.17 on 2026-09-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_cancelar_compra'),
        ('inventory', '0004_cancelar_compra'),
        ('sales', '0004_pedidos_de_marketplace'),
        ('supplies', '0002_estoque_compras_insumos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='refund_of_supply_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='supplies.supplyreceipt'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='supply_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='supplies.supplyreceipt'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.CheckConstraint(condition=models.Q(('supply_receipt__isnull', True), models.Q(('sale__isnull', True), ('receipt__isnull', True)), _connector='OR'), name='cash_supply_single_origin'),
        ),
    ]
