# Generated by Django 5.2.17 on 2026-10-08 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def adjustment_category(apps, schema_editor):
    Category = apps.get_model('finance', 'CashCategory')
    # Não tomar o nome de uma categoria manual já cadastrada pelo dono.
    name = 'Correção de venda'
    suffix = 0
    while Category.objects.using(schema_editor.connection.alias).filter(name__iexact=name).exists():
        suffix += 1
        name = f'Correção de venda (sistema {suffix})'
    Category.objects.using(schema_editor.connection.alias).get_or_create(
        system_key='sale_adjustment', defaults={'name': name, 'direction': 'both', 'counts_in_result': False},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_categorias_do_caixa'),
        ('inventory', '0004_cancelar_compra'),
        ('sales', '0005_salerevision_remove_sale_sale_external_order_unique_and_more'),
        ('supplies', '0004_despesa_por_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(adjustment_category, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='cashentry',
            name='cash_sale_direction_unique',
        ),
        migrations.AddField(
            model_name='cashentry',
            name='sale_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_adjustment', to='sales.salerevision'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.UniqueConstraint(condition=models.Q(('sale_revision__isnull', True)), fields=('sale', 'direction'), name='cash_sale_direction_unique'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.CheckConstraint(condition=models.Q(('sale_revision__isnull', True), ('sale__isnull', False), _connector='OR'), name='cash_revision_requires_sale'),
        ),
    ]
