# Generated by Django 5.2.17 on 2026-09-23 17:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('legacy_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('printing', 'Impressão 3D'), ('resale', 'Revenda')], default='resale', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost_price__gte', 0), ('sale_price__gte', 0)), name='product_prices_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='PrintingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filament_price_kg', models.DecimalField(decimal_places=2, default=115, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_g', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('power_w', models.DecimalField(decimal_places=2, default=200, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('hours', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)])),
                ('energy_price_kwh', models.DecimalField(decimal_places=4, default=Decimal('1.56'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('markup_percent', models.DecimalField(decimal_places=2, default=100, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printing', to='catalog.product')),
            ],
        ),
    ]
