# Generated by Django 5.2.17 on 2026-09-24 17:53

import apps.catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_sku_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("mercado_livre", "Mercado Livre"),
                            ("shopee", "Shopee"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Novo"),
                            ("used", "Usado"),
                            ("reconditioned", "Recondicionado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category_id", models.CharField(blank=True, max_length=80)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drafts",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ImageField(upload_to=apps.catalog.models.product_image_path),
                ),
                ("mime_type", models.CharField(max_length=20)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("size_bytes", models.PositiveIntegerField()),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ListingDraftImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_images",
                        to="catalog.listingdraft",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.productimage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="listingdraft",
            name="images",
            field=models.ManyToManyField(
                related_name="drafts",
                through="catalog.ListingDraftImage",
                to="catalog.productimage",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingdraftimage",
            constraint=models.UniqueConstraint(
                fields=("draft", "image"), name="draft_image_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingdraftimage",
            constraint=models.UniqueConstraint(
                fields=("draft", "position"), name="draft_image_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingdraft",
            constraint=models.UniqueConstraint(
                fields=("product", "channel"), name="draft_product_channel_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__isnull", True), ("price__gte", 0), _connector="OR"
                ),
                name="draft_price_nonnegative",
            ),
        ),
    ]
