# Generated by Django 5.2.17 on 2026-09-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_listingdraft_productimage_listingdraftimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingdraft',
            options={'ordering': ['-updated_at', 'id'], 'permissions': [('publish_listingdraft', 'Pode publicar rascunho no marketplace')]},
        ),
    ]
