# Generated by Django 5.2.17 on 2026-09-29 18:47

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_padronizar_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.catalog.models.validate_gtin]),
        ),
    ]
