# Generated by Django 5.2.17 on 2026-09-30 13:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_categorias_marca_modelo_peso'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingFilament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('roll_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('roll_weight_g', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printing_lines', to='supplies.supply')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filaments', to='catalog.printingprofile')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'filament'), name='printing_filament_unique'), models.CheckConstraint(condition=models.Q(('grams__gt', 0)), name='printing_filament_grams_positive')],
            },
        ),
    ]
