# Generated by Django 5.2.17 on 2026-09-23 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.CharField(default='mercado_livre', max_length=30)),
                ('seller_id', models.CharField(max_length=80)),
                ('item_id', models.CharField(max_length=80)),
                ('user_product_id', models.CharField(blank=True, max_length=80)),
                ('family_id', models.CharField(blank=True, max_length=80)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('marketplace', 'seller_id', 'item_id'), name='listing_external_unique')],
            },
        ),
    ]
