# Generated by Django 5.2.17 on 2026-09-23 21:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['marketplace', 'item_id']},
        ),
        migrations.AlterModelOptions(
            name='outboxevent',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='listing',
            name='remote_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='stock_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='last_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='MarketplaceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('shopee', 'Shopee'), ('mercado_livre', 'Mercado Livre')], max_length=30)),
                ('external_id', models.CharField(help_text='shop_id na Shopee, user_id no ML', max_length=80)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('access_token', models.CharField(blank=True, max_length=512)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['channel', 'external_id'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_id'), name='account_channel_unique')],
            },
        ),
    ]
