# Generated by Django 5.2.17 on 2026-09-25 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_publicacao_ml'),
        ('integrations', '0004_proteger_tokens_e_versao_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='draft',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='catalog.listingdraft'),
        ),
    ]
