# Generated by Django 5.2.17 on 2026-09-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_publicacao_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listing',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
