# Generated by Django 5.2.17 on 2026-09-25 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_historical_item_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='external_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('direct', 'Boca a boca'), ('site', 'Site Jalapão'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('channel', 'external_id'), name='sale_external_order_unique'),
        ),
    ]
