# Generated by Django 5.2.17 on 2026-10-08 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_source(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    Sale.objects.using(schema_editor.connection.alias).exclude(external_id='').update(external_channel=models.F('channel'))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_pedidos_de_marketplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('edit', 'Edição'), ('delete', 'Exclusão')], max_length=10)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('request_key', models.UUIDField(blank=True, null=True)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='sale',
            name='sale_external_order_unique',
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='external_channel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(preserve_source, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_channel', 'external_id'), name='sale_external_order_unique'),
        ),
        migrations.AddField(
            model_name='salerevision',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salerevision',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sales.sale'),
        ),
        migrations.AddConstraint(
            model_name='salerevision',
            constraint=models.UniqueConstraint(fields=('sale', 'request_key'), name='sale_revision_request_unique'),
        ),
    ]
